<?php

namespace Plugin\GHNDelivery\Repository;

use Eccube\Common\EccubeConfig;
use Eccube\Repository\AbstractRepository;
use Plugin\GHNDelivery\Entity\GHNConfig;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GHNConfigRepository extends AbstractRepository
{
    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * ConfigRepository constructor.
     * @param $container
     */
    public function __construct(ManagerRegistry $managerRegistry, EccubeConfig $eccubeConfig, ContainerInterface $container)
    {
        $this->container = $container;
        $this->eccubeConfig = $eccubeConfig;
        parent::__construct($managerRegistry, GHNConfig::class);
    }

    /**
     * @param int $id
     *
     * @return GHNConfig
     */
    public function getOrCreate($id = 1)
    {
        $Config = $this->find($id);
        if (is_null($Config)) {
            $Config = new GHNConfig();
            $Config->setId($id);
            $url = $this->container->get('router')->generate('ghn_callback', [], UrlGeneratorInterface::ABSOLUTE_URL);
            $Config->setCallbackUrl($url);
        }

        return $Config;
    }
}
